# -*- coding: utf-8 -*-
"""FX AGENT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I9Sxw1uXyFhSI_xVobQ3xxqvn3Q8c119
"""

# Раскомментируйте если нужна установка:
!pip install torch torch_geometric stable-baselines3[extra] gymnasium pandas numpy matplotlib

"""1 IMPORTS + MOCKS"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.data import Data
from torch_geometric.nn import GATConv
from typing import Dict, List, Tuple
import gymnasium as gym
from gymnasium import spaces
from stable_baselines3 import TD3
from stable_baselines3.common.torch_layers import BaseFeaturesExtractor
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.noise import NormalActionNoise
from stable_baselines3.common.callbacks import BaseCallback

# ── Глобальные константы ───────────────────────────────────────────────────
CURRENCIES   = ['USD', 'EUR', 'GBP', 'JPY']
N_NODE_FEATS = 2   # [норм_баланс, доля_в_портфеле_USD]
N_EDGE_FEATS = 5   # [log_rate, spread_pct, volatility, momentum, arb_signal]
WINDOW_SIZE  = 20  # сколько тиков истории используем для фичей

# ── Генерация синтетических данных (GBM) ───────────────────────────────────
# Замените на: df = pd.read_csv('your_data.csv')
# Формат CSV: EURUSD_bid, EURUSD_ask, GBPUSD_bid, ...

np.random.seed(42)
N = 5000

base    = {'EURUSD': 1.0850, 'GBPUSD': 1.2720, 'USDJPY': 149.80,
           'EURGBP': 0.8527, 'EURJPY': 162.50, 'GBPJPY': 190.60}
vols = {
    'EURUSD': 0.00020,
    'GBPUSD': 0.00025,
    'USDJPY': 0.00030,
    'EURGBP': 0.00015,
    'EURJPY': 0.00035,
    'GBPJPY': 0.00040,
}

spreads = {'EURUSD': 0.00015, 'GBPUSD': 0.00018, 'USDJPY': 0.018,
           'EURGBP': 0.00012, 'EURJPY': 0.025,   'GBPJPY': 0.030}

# Дрейф — небольшой тренд (позитивный или негативный случайно)
# Это даёт агенту реальный сигнал для держания позиции
# ИЗМЕНЕНО: дрейфы на уровне реального рынка (~0.02% в день)
drifts = {
    'EURUSD':  0.000002,
    'GBPUSD':  0.000003,
    'USDJPY': -0.000005,
    'EURGBP': -0.000001,
    'EURJPY':  0.000003,
    'GBPJPY':  0.000004,
}

data = {}
for pair, p0 in base.items():
    drift = drifts[pair]
    # GBM с дрейфом: μ + σ*ε
    returns = drift + vols[pair] * np.random.randn(N)
    mid     = p0 * np.cumprod(np.exp(returns))
    h       = spreads[pair] / 2.0
    data[f'{pair}_bid'] = mid - h
    data[f'{pair}_ask'] = mid + h

df = pd.DataFrame(data)
print(f'Mock Data: {df.shape[0]} тиков, {df.shape[1]} колонок')
print(df.head(3))

"""2 GRAPH BUILDER"""

# ── Вспомогательные функции ────────────────────────────────────────────────

def get_pair_bid_ask(src: str, dst: str, tick_data: dict) -> Tuple[float, float]:
    """
    Возвращает (bid, ask) для направления src -> dst.
    Если в данных только обратная пара — инвертирует:
      bid(A/B) = 1 / ask(B/A)
      ask(A/B) = 1 / bid(B/A)
    """
    direct  = f'{src}{dst}'
    inverse = f'{dst}{src}'
    if direct in tick_data:
        return tick_data[direct]['bid'], tick_data[direct]['ask']
    elif inverse in tick_data:
        return 1.0 / tick_data[inverse]['ask'], 1.0 / tick_data[inverse]['bid']
    raise KeyError(f'Котировка {src}-{dst} не найдена')


def compute_triangular_arbitrage(
    pairs: List[Tuple[str, str]],
    tick_data: dict,
    currencies: List[str]
) -> dict:
    """
    Перебирает все циклы A->B->C->A.
    Для каждого ребра сохраняет максимальную доходность цикла.
    Значение > 0 = арбитражная возможность существует.
    """
    arb = {pair: 0.0 for pair in pairs}
    for a in currencies:
        for b in currencies:
            if a == b: continue
            for c in currencies:
                if c == a or c == b: continue
                try:
                    r_ab, _ = get_pair_bid_ask(a, b, tick_data)
                    r_bc, _ = get_pair_bid_ask(b, c, tick_data)
                    r_ca, _ = get_pair_bid_ask(c, a, tick_data)
                    cycle   = r_ab * r_bc * r_ca - 1.0
                    for edge in [(a,b),(b,c),(c,a)]:
                        if edge in arb:
                            arb[edge] = max(arb[edge], cycle)
                except KeyError:
                    continue
    return arb


# ── Основной класс ─────────────────────────────────────────────────────────

class FxGraphBuilder:
    def __init__(self, currencies: List[str] = CURRENCIES):
        self.currencies = currencies
        self.n_nodes    = len(currencies)

        src_list, dst_list, self.edge_pairs = [], [], []
        for i, src in enumerate(currencies):
            for j, dst in enumerate(currencies):
                if i != j:
                    src_list.append(i)
                    dst_list.append(j)
                    self.edge_pairs.append((src, dst))

        self.edge_index = torch.tensor([src_list, dst_list], dtype=torch.long)
        self.n_edges    = len(self.edge_pairs)  # 12

    def _parse_tick(self, row: pd.Series) -> dict:
        tick_data = {}
        pairs = set(col.split('_')[0] for col in row.index if '_bid' in col or '_ask' in col)
        for pair in pairs:
            if f'{pair}_bid' in row.index and f'{pair}_ask' in row.index:
                tick_data[pair] = {
                    'bid': float(row[f'{pair}_bid']),
                    'ask': float(row[f'{pair}_ask'])
                }
        return tick_data

    def build(self, df_window: pd.DataFrame, agent_balances: Dict[str, float]) -> Data:
        tick_data   = self._parse_tick(df_window.iloc[-1])
        arb_signals = compute_triangular_arbitrage(self.edge_pairs, tick_data, self.currencies)

        # ── Признаки рёбер ──────────────────────────────────────────────────
        edge_features = []
        for src, dst in self.edge_pairs:
            try:
                bid, ask   = get_pair_bid_ask(src, dst, tick_data)
                mid        = (bid + ask) / 2.0
                spread_pct = (ask - bid) / mid if mid > 0 else 0.0

                p_fwd, p_inv = f'{src}{dst}', f'{dst}{src}'
                if f'{p_fwd}_bid' in df_window.columns:
                    hist = (df_window[f'{p_fwd}_bid'] + df_window[f'{p_fwd}_ask']) / 2.0
                elif f'{p_inv}_bid' in df_window.columns:
                    hist = 1.0 / ((df_window[f'{p_inv}_bid'] + df_window[f'{p_inv}_ask']) / 2.0)
                else:
                    hist = pd.Series([mid])

                log_rets   = np.log(hist / hist.shift(1)).dropna()
                volatility = float(log_rets.std()) if len(log_rets) > 2 else 0.0
                momentum   = float((mid / hist.iloc[0]) - 1.0) if len(hist) > 1 else 0.0

                edge_features.append([
                    np.log(max(mid, 1e-6)),       # log_rate
                    spread_pct,               # spread_pct
                    volatility,               # volatility
                    momentum,                 # momentum
                    arb_signals[(src, dst)],  # arb_signal
                ])
            except KeyError:
                edge_features.append([0.0, 0.0, 0.0, 0.0, 0.0])

        # ── Признаки узлов ──────────────────────────────────────────────────
        total_usd  = 1e-9
        usd_values = {}
        for ccy in self.currencies:
            amount = agent_balances.get(ccy, 0.0)
            if ccy == 'USD':
                val = amount
            else:
                try:
                    bid, _ = get_pair_bid_ask(ccy, 'USD', tick_data)
                    val    = amount * bid
                except KeyError:
                    val = 0.0
            usd_values[ccy] = val
            total_usd += val

        node_features = []
        for ccy in self.currencies:
            amount = agent_balances.get(ccy, 0.0)
            node_features.append([
                amount / (total_usd + 1e-9),
                usd_values[ccy] / (total_usd + 1e-9),
            ])

        return Data(
            x          = torch.tensor(node_features, dtype=torch.float32),
            edge_index = self.edge_index,
            edge_attr  = torch.tensor(edge_features, dtype=torch.float32),
        )


# ── Тест ───────────────────────────────────────────────────────────────────
builder = FxGraphBuilder()
g = builder.build(
    df_window      = df.iloc[:WINDOW_SIZE],
    agent_balances = {'USD': 10000.0, 'EUR': 0.0, 'GBP': 0.0, 'JPY': 0.0}
)
print(f'nodes:      {g.x.shape}')
print(f'edge_index: {g.edge_index.shape}')
print(f'edge_attr:  {g.edge_attr.shape}')

"""3 FXArbitrageEnv"""

class FXArbitrageEnv(gym.Env):
    """
    Обновлённая среда с тремя ключевыми улучшениями:

    1. Action space — delta [-1, 1] для каждой non-USD валюты
       Агент говорит "сколько % портфеля переложить", а не "каков целевой вес"
       Если |delta| < TRADE_THRESHOLD → hold, ничего не делаем

    2. Reward = Δ NAV - штраф_за_turnover + hold_bonus
       Агент штрафуется за лишние сделки и поощряется за удержание позиции

    3. prev_weights отслеживаются между шагами
       Агент видит насколько изменился портфель относительно предыдущего шага
    """

    TRADE_THRESHOLD  = 0.05   # меньше 3% изменения → держим позицию
    TURNOVER_PENALTY = 0.1   # штраф за оборот (λ)
    HOLD_BONUS = 0.05         # бонус за бездействие
    MAX_TRADE_FRAC   = 0.3

    def __init__(
        self,
        builder: FxGraphBuilder,
        df_data: pd.DataFrame,
        window_size: int           = WINDOW_SIZE,
        initial_balance_usd: float = 10_000.0,
        max_drawdown: float        = 0.50,
    ):
        super().__init__()
        self.builder             = builder
        self.df_data             = df_data.reset_index(drop=True)
        self.window_size         = window_size
        self.initial_balance_usd = initial_balance_usd
        self.max_drawdown        = max_drawdown
        self.max_steps           = len(df_data) - 1

        # Action: дельты для [EUR, GBP, JPY] от -1 до +1
        # +1 = вложить 100% портфеля в эту валюту
        # -1 = полностью выйти из этой валюты
        # 0  = ничего не делать (hold)
        self.action_space = spaces.Box(
            low=0, high=1.0, shape=(3,), dtype=np.float32
        )
        self.observation_space = spaces.Dict({
            'nodes': spaces.Box(-np.inf, np.inf, shape=(4, N_NODE_FEATS), dtype=np.float32),
            'edges': spaces.Box(-np.inf, np.inf, shape=(12, N_EDGE_FEATS), dtype=np.float32),
        })

        self.balances          = {}
        self.portfolio_history = []
        self.prev_weights      = np.array([1.0, 0.0, 0.0, 0.0])  # [USD, EUR, GBP, JPY]
        self.current_step      = window_size

    # ── Вспомогательные методы ────────────────────────────────────────────

    def _get_nav(self, tick_data: dict) -> float:
        nav = self.balances['USD']
        for ccy in ['EUR', 'GBP', 'JPY']:
            amount = self.balances.get(ccy, 0.0)
            if amount > 1e-9:
                try:
                    bid, _ = get_pair_bid_ask(ccy, 'USD', tick_data)
                    nav   += amount * bid
                except KeyError:
                    pass
        return nav

    def _get_weights(self, tick_data: dict, nav: float) -> np.ndarray:
        """Текущие веса портфеля [USD, EUR, GBP, JPY]."""
        weights = []
        for ccy in self.builder.currencies:
            amount = self.balances.get(ccy, 0.0)
            if ccy == 'USD':
                weights.append(amount / nav)
            else:
                try:
                    bid, _ = get_pair_bid_ask(ccy, 'USD', tick_data)
                    weights.append(amount * bid / nav)
                except KeyError:
                    weights.append(0.0)
        return np.array(weights)

    def _execute_trade(self, ccy: str, delta_usd: float, tick_data: dict):
        """
        Все сделки проводим через прямые котировки CCY/USD:
          Покупка CCY: тратим delta_usd USD, получаем delta_usd / ask_CCY_USD
          Продажа CCY: получаем delta_usd USD, отдаём delta_usd / bid_CCY_USD
        """
        try:
            bid_ccy_usd, ask_ccy_usd = get_pair_bid_ask(ccy, 'USD', tick_data)
        except KeyError:
            return

        if delta_usd > 1e-6:
            # Покупаем CCY: платим Ask (худший курс для нас)
            if self.balances['USD'] >= delta_usd:
                self.balances['USD'] -= delta_usd
                self.balances[ccy]   += delta_usd / ask_ccy_usd  # ← всегда делим

        elif delta_usd < -1e-6:
            # Продаём CCY: получаем Bid (худший курс для нас)
            amount_to_sell_usd = abs(delta_usd)
            amount_ccy         = amount_to_sell_usd / bid_ccy_usd  # ← всегда делим
            if self.balances.get(ccy, 0.0) >= amount_ccy:
                self.balances[ccy]   -= amount_ccy
                self.balances['USD'] += amount_to_sell_usd

    # ── Основные методы Gym ───────────────────────────────────────────────

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)
        self.current_step      = self.window_size
        self.balances          = {
            'USD': self.initial_balance_usd,
            'EUR': 0.0,
            'GBP': 0.0,
            'JPY': 0.0
        }
        self.portfolio_history = [self.initial_balance_usd]
        self.prev_weights      = np.array([1.0, 0.0, 0.0, 0.0])
        return self._get_obs(), {}

    def _get_obs(self) -> dict:
        window = self.df_data.iloc[self.current_step - self.window_size : self.current_step]
        graph  = self.builder.build(df_window=window, agent_balances=self.balances)
        return {
            'nodes': graph.x.numpy().astype(np.float32),
            'edges': graph.edge_attr.numpy().astype(np.float32),
        }

    def step(self, action: np.ndarray):
        tick_data  = self.builder._parse_tick(self.df_data.iloc[self.current_step])
        nav_before = self._get_nav(tick_data)

        non_usd  = ['EUR', 'GBP', 'JPY']
        turnover = 0.0
        traded   = False

        # ── ИЗМЕНЕНО: считаем текущие веса и торгуем до целевых ──────────
        current_weights = self._get_weights(tick_data, nav_before)
        # current_weights = [w_USD, w_EUR, w_GBP, w_JPY]

        for i, ccy in enumerate(non_usd):
            # action[i] = желаемый вес для этой валюты (0 до 1)
            # Интерпретируем action как ЦЕЛЕВОЙ вес, а не дельту
            target_weight  = np.clip(float(action[i]), 0.0, self.MAX_TRADE_FRAC)
            current_weight = current_weights[i + 1]  # +1 потому что [0]=USD
            delta_weight   = target_weight - current_weight

            if abs(delta_weight) < self.TRADE_THRESHOLD:
                continue

            delta_usd = delta_weight * nav_before
            self._execute_trade(ccy, delta_usd, tick_data)
            turnover += abs(delta_weight)
            traded    = True
        # ─────────────────────────────────────────────────────────────────

        nav_after = self._get_nav(tick_data)
        current_weights = self._get_weights(tick_data, nav_after)

        # Компонент 1: изменение NAV
        delta_nav = nav_after - nav_before

        # Компонент 2: штраф за оборот (чем больше торгуем — тем больше штраф)
        turnover_penalty = self.TURNOVER_PENALTY * turnover * nav_before / 10_000

        # Компонент 3: бонус за hold (агент не торговал → маленький плюс)
        hold_bonus = self.HOLD_BONUS if not traded else 0.0

        reward = delta_nav - turnover_penalty + hold_bonus

        self.prev_weights = current_weights
        self.portfolio_history.append(nav_after)

        # ── Условие завершения ────────────────────────────────────────────
        self.current_step += 1
        done = self.current_step >= self.max_steps

        peak = max(self.portfolio_history)
        if (peak - nav_after) / peak > self.max_drawdown:
            done    = True
            reward -= 50.0

        info = {
            'nav':      nav_after,
            'turnover': turnover,
            'traded':   traded,
            'weights':  current_weights,
        }
        return self._get_obs(), float(reward), done, False, info


# ── Тест ──────────────────────────────────────────────────────────────────
env    = FXArbitrageEnv(builder=builder, df_data=df)
obs, _ = env.reset()
print(f'obs[nodes]: {obs["nodes"].shape}')
print(f'obs[edges]: {obs["edges"].shape}')

# Тест 1: агент держит позицию (маленькие дельты → hold)
obs, reward, done, _, info = env.step(np.array([0.01, 0.01, 0.01], dtype=np.float32))
print(f'\nHold action:')
print(f'  Reward:  {reward:.4f}  (должен быть ~+0.1 hold_bonus)')
print(f'  Traded:  {info["traded"]}')

# Тест 2: агент покупает EUR на 20% портфеля
obs, reward, done, _, info = env.step(np.array([0.20, 0.0, 0.0], dtype=np.float32))
print(f'\nBuy EUR 20%:')
print(f'  Reward:  {reward:.4f}  (будет отрицательным из-за спреда)')
print(f'  Weights: {info["weights"].round(3)}')
print(f'  NAV:     ${info["nav"]:.4f}')

"""4 GRAPH EXTRACTOR"""

class FxGraphExtractor(BaseFeaturesExtractor):
    """
    GAT Feature Extractor для Stable-Baselines3.

    Принимает батч {'nodes': (B,4,2), 'edges': (B,12,5)},
    строит батчированный граф PyG, прогоняет через два слоя GAT.
    Выдаёт плоский вектор (B, features_dim) для Actor и Critic TD3.

    Архитектура:
      GATConv(2  → 16, heads=4, edge_dim=5) → LeakyReLU → (B*4, 64)
      GATConv(64 → 32, heads=1, edge_dim=5) → LeakyReLU → (B*4, 32)
      Reshape                               →            (B, 128)
      Linear(128 → features_dim) + ReLU + LayerNorm
    """

    def __init__(self, observation_space: spaces.Dict, features_dim: int = 128):
        super().__init__(observation_space, features_dim)

        self.n_nodes = observation_space.spaces['nodes'].shape[0]  # 4
        n_node_feats = observation_space.spaces['nodes'].shape[1]  # 2
        n_edge_feats = observation_space.spaces['edges'].shape[1]  # 5

        # Слой 1: 4 головы внимания, каждая видит признаки рёбер (спред, арбитраж)
        self.gat1 = GATConv(
            in_channels    = n_node_feats,
            out_channels   = 16,
            heads          = 4,
            edge_dim       = n_edge_feats,
            add_self_loops = False,
            dropout        = 0.1,
        )
        # Слой 2: агрегация в 32-мерный эмбеддинг на каждый узел
        self.gat2 = GATConv(
            in_channels    = 16 * 4,  # 4 головы от gat1
            out_channels   = 32,
            heads          = 1,
            edge_dim       = n_edge_feats,
            add_self_loops = False,
        )

        # Топология графа: полносвязный, 4 узла, без петель (12 рёбер)
        # register_buffer → автоматически переносится на GPU вместе с моделью
        src, dst = [], []
        for i in range(self.n_nodes):
            for j in range(self.n_nodes):
                if i != j:
                    src.append(i)
                    dst.append(j)
        self.register_buffer(
            'base_edge_index',
            torch.tensor([src, dst], dtype=torch.long)
        )

        # Финальная проекция: 4 узла × 32 фичи → features_dim
        self.linear = nn.Sequential(
            nn.Linear(self.n_nodes * 32, features_dim),
            nn.ReLU(),
            nn.LayerNorm(features_dim),
        )

    def forward(self, observations: dict) -> torch.Tensor:
        nodes = observations['nodes']  # (B, 4, 2)
        edges = observations['edges']  # (B, 12, 5)
        B     = nodes.shape[0]
        device = nodes.device

        # Вытягиваем батч в плоский формат PyG
        x         = nodes.view(B * self.n_nodes, -1)  # (B*4, 2)
        edge_attr = edges.view(B * 12, -1)             # (B*12, 5)

        # Сдвигаем индексы рёбер для каждого графа в батче
        edge_index = torch.cat(
            [self.base_edge_index + b * self.n_nodes for b in range(B)],
            dim=1
        )

        # GAT прогон
        x = F.leaky_relu(self.gat1(x, edge_index, edge_attr))  # (B*4, 64)
        x = F.leaky_relu(self.gat2(x, edge_index, edge_attr))  # (B*4, 32)

        # Reshape и проекция
        x = x.view(B, self.n_nodes * 32)  # (B, 128)
        return self.linear(x)             # (B, features_dim)


# ── Тест ───────────────────────────────────────────────────────────────────
# Проверяем что экстрактор принимает правильные размерности
_test_env = FXArbitrageEnv(builder=builder, df_data=df)
_obs, _   = _test_env.reset()

_extractor = FxGraphExtractor(_test_env.observation_space, features_dim=128)

_nodes = torch.tensor(_obs['nodes']).unsqueeze(0)  # (1, 4, 2)
_edges = torch.tensor(_obs['edges']).unsqueeze(0)  # (1, 12, 5)
_out   = _extractor({'nodes': _nodes, 'edges': _edges})

print(f'Вход  nodes: {_nodes.shape}')
print(f'Вход  edges: {_edges.shape}')
print(f'Выход:       {_out.shape}  ← (1, 128) идёт в Actor/Critic TD3')

"""5 TD3 обучение"""

# ── Колбэк ───────────────────────────────────────────────────────────────
class PortfolioLoggerCallback(BaseCallback):
    def __init__(self, log_every=500, verbose=0):
        super().__init__(verbose)
        self.log_every       = log_every
        self.episode_rewards = []
        self.episode_navs    = []
        self._ep_reward      = 0.0
        self._window_navs    = []
        self._window_rewards = []

    def _on_step(self) -> bool:
        info    = self.locals['infos'][0]
        reward  = self.locals['rewards'][0]
        nav     = info.get('nav', 0)

        self._ep_reward += reward
        self._window_navs.append(nav)
        self._window_rewards.append(reward)

        if self.num_timesteps % self.log_every == 0:
            w_nav = self._window_navs[-self.log_every:]
            w_rew = self._window_rewards[-self.log_every:]

            avg_nav  = np.mean(w_nav)
            min_nav  = np.min(w_nav)
            max_nav  = np.max(w_nav)
            avg_rew  = np.mean(w_rew)
            ep_count = len(self.episode_rewards)
            ep_avg_r = np.mean(self.episode_rewards[-10:]) if ep_count > 0 else 0.0

            print(
                f'[{self.num_timesteps:>6}/100000] '
                f'NAV: ${avg_nav:>9,.2f} '
                f'[${min_nav:>8,.2f} – ${max_nav:>8,.2f}]  '
                f'R_step: {avg_rew:>+7.5f}  '
                f'R_ep(last10): {ep_avg_r:>+8.4f}  '
                f'turnover: {info.get("turnover", 0):.4f}  '
                f'traded: {"✅" if info.get("traded", False) else "❌"}  '
                f'episodes: {ep_count}'
            )

        if self.locals['dones'][0]:
            self.episode_rewards.append(self._ep_reward)
            self.episode_navs.append(nav)
            self._ep_reward = 0.0

        return True


# ── Train / Test split ────────────────────────────────────────────────────
train_df = df.iloc[:4000].reset_index(drop=True)
test_df  = df.iloc[4000:].reset_index(drop=True)

train_env = DummyVecEnv([lambda: FXArbitrageEnv(builder=builder, df_data=train_df)])

# ── Policy kwargs ─────────────────────────────────────────────────────────
policy_kwargs = dict(
    features_extractor_class  = FxGraphExtractor,
    features_extractor_kwargs = dict(features_dim=128),
    net_arch                  = [128, 64],
)

# ── Action noise ──────────────────────────────────────────────────────────
n_actions    = train_env.action_space.shape[-1]
action_noise = NormalActionNoise(
    mean  = np.zeros(n_actions),
    sigma = 0.08 * np.ones(n_actions)
)

# ── Модель ────────────────────────────────────────────────────────────────
model = TD3(
    'MultiInputPolicy',
    train_env,
    policy_kwargs   = policy_kwargs,
    learning_rate   = 1e-4,
    batch_size      = 256,
    buffer_size     = 100_000,
    action_noise    = action_noise,
    learning_starts = 2000,
    train_freq      = 1,
    gradient_steps  = 1,
    verbose         = 0,
)

# ── Запуск ────────────────────────────────────────────────────────────────
callback = PortfolioLoggerCallback(log_every=500)

print('Старт обучения TD3 (100k шагов)...')
model.learn(total_timesteps=100_000, callback=callback)
model.save('td3_fx_graph_v2')
print('Готово. Модель сохранена: td3_fx_graph_v2.zip')

# Check what actions TD3 is actually outputting
obs_test, _ = FXArbitrageEnv(builder=builder, df_data=test_df).reset()
for _ in range(10):
    action, _ = model.predict(obs_test, deterministic=False)
    print(f'action: {action.round(3)}')

# Быстрая проверка среды — 5 шагов вручную
env    = FXArbitrageEnv(builder=builder, df_data=train_df)
obs, _ = env.reset()

for i in range(5):
    action = np.array([0.20, 0.15, 0.10], dtype=np.float32)  # фиксированное действие
    obs, reward, done, _, info = env.step(action)
    print(f'Шаг {i+1}: NAV=${info["nav"]:.2f} | '
          f'traded={info["traded"]} | '
          f'turnover={info["turnover"]:.3f} | '
          f'weights={info["weights"].round(3)}')

# Изолированный тест — без DummyVecEnv
env    = FXArbitrageEnv(builder=builder, df_data=train_df)
obs, _ = env.reset()

for step in range(1000):
    action = train_env.action_space.sample()  # случайные действия
    obs, reward, done, _, info = env.step(action)

    if step % 100 == 0:
        print(f'Шаг {step:>4}: NAV=${info["nav"]:.2f} | '
              f'traded={info["traded"]} | '
              f'turnover={info["turnover"]:.3f}')

    if done:
        print(f'  → Episode done at step {step}, resetting...')
        obs, _ = env.reset()

# Сначала убеждаемся что данные новые
print(f'USDJPY диапазон в df: {df["USDJPY_bid"].min():.2f} – {df["USDJPY_bid"].max():.2f}')
print(f'train_df строк: {len(train_df)}')

# Явно пересоздаём всё
builder  = FxGraphBuilder()
train_df = df.iloc[:4000].reset_index(drop=True)
test_df  = df.iloc[4000:].reset_index(drop=True)

# Пересоздаём среду
env    = FXArbitrageEnv(builder=builder, df_data=train_df)
obs, _ = env.reset()

FIXED_ACTION = np.array([0.20, 0.15, 0.10], dtype=np.float32)

for step in range(1000):
    obs, reward, done, _, info = env.step(FIXED_ACTION)
    if step % 100 == 0:
        w = info["weights"]
        print(f'Шаг {step:>4}: NAV=${info["nav"]:.2f} | '
              f'USD={w[0]:.2f} EUR={w[1]:.2f} GBP={w[2]:.2f} JPY={w[3]:.2f} | '
              f'traded={info["traded"]}')
    if done:
        obs, _ = env.reset()

# Смотрим что происходит с курсом JPY/USD в данных
fig, axes = plt.subplots(1, 2, figsize=(14, 4))

# График 1: USDJPY mid
usdjpy_mid = (df['USDJPY_bid'] + df['USDJPY_ask']) / 2
axes[0].plot(usdjpy_mid[:1000])
axes[0].set_title('USDJPY mid (первые 1000 тиков)')
axes[0].set_ylabel('USDJPY')

# График 2: JPY/USD = 1/USDJPY
jpyusd = 1.0 / usdjpy_mid
axes[1].plot(jpyusd[:1000])
axes[1].set_title('JPY/USD = 1/USDJPY')
axes[1].set_ylabel('JPY/USD')

plt.tight_layout()
plt.show()

print(f'USDJPY диапазон: {usdjpy_mid.min():.2f} – {usdjpy_mid.max():.2f}')
print(f'JPY/USD диапазон: {jpyusd.min():.6f} – {jpyusd.max():.6f}')
print(f'JPY/USD изменение за 1000 тиков: {(jpyusd.iloc[999]/jpyusd.iloc[0]-1)*100:.1f}%')

"""6 Evaluation"""

def evaluate(model, df_eval, builder, n_episodes=3):
    """Прогоняет обученного агента на тестовых данных."""
    all_histories = []

    for ep in range(n_episodes):
        env    = FXArbitrageEnv(builder=builder, df_data=df_eval)
        obs, _ = env.reset()
        done   = False

        while not done:
            action, _ = model.predict(obs, deterministic=True)
            obs, _, done, _, info = env.step(action)

        final_nav = env.portfolio_history[-1]
        ret_pct   = (final_nav / env.initial_balance_usd - 1) * 100
        print(f'  Эпизод {ep+1}: NAV ${final_nav:.2f}  ({ret_pct:+.2f}%)')
        all_histories.append(env.portfolio_history)

    return all_histories


# ── Запуск оценки ─────────────────────────────────────────────────────────
print('Оценка на тестовых данных:')
test_histories = evaluate(model, test_df, builder, n_episodes=3)

# ── Графики ───────────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(18, 4))

# График 1: Reward по эпизодам обучения
axes[0].plot(callback.episode_rewards, color='steelblue', linewidth=1.2)
axes[0].axhline(0, color='red', linestyle='--', alpha=0.5)
axes[0].set_title('Reward per Episode (Train)')
axes[0].set_xlabel('Эпизод')
axes[0].set_ylabel('Суммарный Reward')

# График 2: NAV по эпизодам обучения
axes[1].plot(callback.episode_navs, color='seagreen', linewidth=1.2)
axes[1].axhline(10_000, color='red', linestyle='--', alpha=0.5, label='Начальный капитал')
axes[1].legend()
axes[1].set_title('Final NAV per Episode (Train)')
axes[1].set_xlabel('Эпизод')
axes[1].set_ylabel('USD')

# График 3: Траектория NAV на тесте
for i, hist in enumerate(test_histories):
    axes[2].plot(hist, linewidth=1.5, label=f'Эпизод {i+1}')
axes[2].axhline(10_000, color='red', linestyle='--', alpha=0.5, label='Начальный капитал')
axes[2].legend()
axes[2].set_title('NAV Trajectory (Test)')
axes[2].set_xlabel('Шаг')
axes[2].set_ylabel('USD')

plt.tight_layout()
plt.savefig('results.png', dpi=120)
plt.show()

print(f'\nСтатистика обучения:')
print(f'  Всего эпизодов:     {len(callback.episode_rewards)}')
print(f'  Лучший reward:      {max(callback.episode_rewards):.4f}')
print(f'  Средний NAV (последние 10 эп.): ${sum(callback.episode_navs[-10:])/10:.2f}')